In [5]:
import pandas as pd
dados = pd.read_csv("C:/Users/marce/ansel/Desktop/GSPC.csv")

dados = dados.drop("Date" , axis= 1) #apagando uma coluna

dados [-2::] #pegarei as duas ultimas como metodo comparativo para o machine learning

amanha = dados[-1::] #apenas última linha, preciso excluí-lá do conjunto

base = dados.drop(dados[-1::].index , axis = 0) #mostra todos menos a ultima linha, exclui do conjunto
base.tail()

#o nosso objetivo é saber se o valor do amanha será maior ou menor do que o hoje

,Open,High,Low,Close,Adj Close,Volume
17212,2702.429932,2729.340088,2702.429932,2724.010010,2724.010010,3561050000
17213,2720.979980,2722.500000,2700.679932,2705.270020,2705.270020,4235370000
17214,2718.699951,2736.929932,2718.699951,2734.620117,2734.620117,3684130000
17215,2741.669922,2749.159912,2740.540039,2746.870117,2746.870117,3376510000
17216,2748.459961,2752.610107,2739.510010,2748.800049,2748.800049,3517790000